apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "n8n.fullname" . }}-secrets
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # Empty tells the driver to use the system-assigned kubelet identity
    keyvaultName: {{ .Values.keyvault.name | quote }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
        - |
          objectName: n8n-encryption-key
          objectType: secret
  secretObjects:
    - secretName: {{ include "n8n.fullname" . }}-db-secrets
      type: Opaque
      data:
        - objectName: postgres-password
          key: postgres-password
        - objectName: redis-password
          key: redis-password
        - objectName: n8n-encryption-key
          key: n8n-encryption-key