apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-main
  labels:
    {{- include "n8n.main.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-worker
  labels:
    {{- include "n8n.worker.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  labels:
    {{- include "n8n.webhook.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false
