apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-main
  labels:
    {{- include "n8n.main.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-worker
  labels:
    {{- include "n8n.worker.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  labels:
    {{- include "n8n.webhook.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-postgres
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-redis
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
automountServiceAccountToken: false