apiVersion: v2
name: n8n
description: A production-ready custom Helm chart for deploying n8n in Queue Mode
type: application
version: 1.0.1 # Version of helm template
appVersion: "1.94.1" # version of actual n8n app we are running

