global:
  environment: dev

n8n:
  image:
    repository: n8nio/n8n
    tag: "1.94.1"
    pullPolicy: IfNotPresent

  main:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 512Mi

  worker:
    replicaCount: 1 # Starts at 1, KEDA will autoscale this later
    resources:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi

  webhook:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  
postgres:
  image:
    repository: postgres
    tag: "16.3"
    pullPolicy: IfNotPresent
  storage: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

redis:
  image:
    repository: redis
    tag: "7.2.5"
    pullPolicy: IfNotPresent
  storage: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

ingress:
  enabled: true
  className: addon-http-application-routing # default aks ingress class or nginx
  host: n8n.dev.local
  tlsSecret: n8n-tls
  controllerNamespace: ingress-nginx

keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 300
  redis:
    listName: "bull:jobs:wait"
    listLength: "5"

keyvault:
  name: "n8n-dev-kv-ajay789"
  tenantId: "823fc44f-0584-4327-8fc8-e26608640a83"
  clientId: "a73f5abb-22e1-4faa-85a3-ecb8b8b223c2"

monitoring:
  enabled: true