apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-dev
  namespace: argocd
spec: 
  project: n8n-project
  source:
    chart: n8n
    repoURL: n8ndevacrajay789.azurecr.io/helm
    targetRevision: 1.0.0-618ba42
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # create dev namespace if not exist