apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-gatekeeper-constraints
  namespace: argocd
spec:
  project: n8n-project
  source:
    repoURL: https://github.com/AjaySusanth/n8n-production-platform.git
    targetRevision: fix/audit-fixes
    path: gitops/argocd/gatekeeper/constraints
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
