apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: n8n-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  description: "n8n Workflow Automation Platform Project"
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: keda
      server: https://kubernetes.default.svc
    - namespace: monitoring  
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: gatekeeper-system
      server: https://kubernetes.default.svc

  sourceRepos:
    - 'https://github.com/AjaySusanth/n8n-production-platform.git'
    - 'https://kedacore.github.io/charts'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://open-policy-agent.github.io/gatekeeper/charts'
    - 'n8ndevacrajay789.azurecr.io/helm'
  clusterResourceWhitelist: 
    - group: '*'
      kind: '*'