apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-prometheus
  namespace: argocd

spec:
  project: n8n-project
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "56.6.2"
    helm:
      values: |
        grafana:
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: ALL

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
