apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/AjaySusanth/n8n-production-platform.git
    targetRevision: HEAD
    path: gitops/argocd
    directory:
      recurse: false   # Only top-level files — skips gatekeeper/ subdirectory
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
